<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

## Exercise 1 (Total recall)

|    Term    |                                                             Brief description                                                            |
|:----------:|:----------------------------------------------------------------------------------------------------------------------------------------:|
| Subsetting | Selecting a portion of data in a list or array                                                                                            |
| Indexing   | Selecting a single element from a list or array based on their numerical position                                                           |
| Slicing    | Selecting a subset/range of data in a list or array based on a start and/or end index                                                    |
| Masking    | Selecting a subset of data in a list or array based on a true/false condition, returns only the elements that satisfy the true condition |

## Exercise 2 (Show me the ‘odd’ letters)

In [16]:
import numpy as np

np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])
np_array_2d_numbers = np_array_2d[:,0].astype(int)
np_array_2d_remainder = np_array_2d_numbers%2
np_array_2d_tf = np_array_2d_remainder == 1
print(np_array_2d[np_array_2d_tf][:,1])


['A' 'C' 'E' 'G' 'I']


## Exercise 3  

In [36]:
np_array_ex3 = np.array([[66, 50, 57, -1, -1],
                         [92, -1, 88, -1, -1],
                         [75, -1, -1, 76, -1],
                         [-1, 51, 87, -1, -1],
                         [71, -1, 67, -1, 69]])
np_array_ex3_b50 = np_array_ex3 < 50
np_array_ex3_50 = np_array_ex3 == 50
np_array_ex3_a50 = np_array_ex3 > 50

np_array_ex3[np_array_ex3_b50] = -1
np_array_ex3[np_array_ex3_50] = 0
np_array_ex3[np_array_ex3_a50] = 1

print(np_array_ex3)

[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
