<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

# What to expect in this chapter

# 1 Lists, Arrays & Dictionaries

## 1.1 Let’s compare

In [1]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

In [2]:
import numpy as np
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

In [3]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}

## 1.2 Accessing data from a list (or array)

In [4]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

In [5]:
py_real_names[0]

'Natasha Romanoff'

In [8]:
py_super_names[0]

'Black Widow'

In [9]:
py_super_names[2]    # Forward indexing 

'Doctor Strange'

In [10]:
                     # We need to know the size 
                     # beforehand for this to work.
py_super_names[-1]   # Reverse indexing

'Doctor Strange'

## 1.3 Accessing data from a dictionary

In [11]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}                  

In [12]:
superhero_info["Natasha Romanoff"]

'Black Widow'

In [13]:
superhero_info.keys()

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])

In [14]:
superhero_info.values()

dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

## 1.4 Higher dimensional lists

In [16]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]
py_superhero_info[0][0]

'Natasha Romanoff'

# 2 Lists vs. Arrays

## 2.1 Size

In [17]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array

In [27]:
print(len(py_list_2d))
print(len(np_array_2d))
print(np_array_2d.shape)

10
10
(10, 2)


## 2.2 Arrays are fussy about type

In [28]:
py_list = [1, 1.5, 'A']
np_array = np.array(py_list)

In [30]:
py_list

[1, 1.5, 'A']

In [31]:
np_array

array(['1', '1.5', 'A'], dtype='<U32')

## 2.3 Adding a number

In [32]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         # Reusing the Python list
                                     # to create a NEW
                                     # NumPy array

In [33]:
np_array + 10

array([11, 12, 13, 14, 15])

In [34]:
py_list + 10        # Won't work!

TypeError: can only concatenate list (not "int") to list

## 2.4 Adding another list

In [35]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

In [36]:
py_list_1 + py_list_2

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [37]:
np_array_1 + np_array_2

array([11, 22, 33, 44, 55])

## 2.5 Multiplying by a Number

In [38]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [40]:
py_list*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [41]:
np_array*2

array([ 2,  4,  6,  8, 10])

## 2.6 Squaring

In [42]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [43]:
np_array**2

array([ 1,  4,  9, 16, 25])

In [44]:
py_list**2                      # Won't work!  

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

## 2.7 Asking questions

In [45]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [47]:
py_list == 3     # Works, but what IS the question?

False

In [50]:
py_list > 3      # Won't work!

TypeError: '>' not supported between instances of 'list' and 'int'

In [48]:
np_array == 3  

array([False, False,  True, False, False])

In [49]:
np_array > 3  

array([False, False, False,  True,  True])

## 2.8 Mathematics

In [51]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [52]:
sum(py_list)     # sum() is a base Python function

15

In [53]:
max(py_list)     # max() is a base Python function

5

In [54]:
min(py_list)     # min() is a base Python function

1

In [60]:
py_list.sum()   # Won't work!

AttributeError: 'list' object has no attribute 'sum'

In [55]:
np_array.sum()

np.int64(15)

In [56]:
np_array.max()

np.int64(5)

In [57]:
np_array.min()

np.int64(1)

In [58]:
np_array.mean()

np.float64(3.0)

In [59]:
np_array.std()

np.float64(1.4142135623730951)

## Footnotes